# Generated by Django 3.2.12 on 2022-03-31 18:58

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', blog.models.UserManager()),
            ],
        ),
    ]
