# Generated by Django 3.2.12 on 2022-03-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(default='test', upload_to='blog/static/blog/images'),
        ),
    ]
